### ISSUE TITLE
[question] because we can't get coverage info for test case generated at run time

### ISSUE THREAD

**Issue by RoelofWobben** [stryker-mutator/stryker-net#1095]
Hello, 

Im learning c# by doing a bootcamp and we now learning to test and I have tried to experiment with stryker by using one of the homeworks. 

But I see warnings like this and I have no idea what to do to solve them or have the knowlegde to know if I can ignore it. 

The error messages are : 

```
[18:03:34 WRN] Runner 1: Each mutant will be tested against BootCamp.Chapter.Tests.PokerComboTests.Greater__Given_Set1_Is_Smaller_Set2_Returns_Expected), because we can't get coverage info for test case generated at run time
```

The test can be  found here : https://github.com/RoelofWobben/CSharp-From-Zero-To-Hero/blob/Chapter4/Homework/2/Tests/BootCamp.Chapter.Tests/PokerComboTests.cs

Can someone help me figure out how to make this work ? 

Roelof

**Comment by Mobrockers** [comment]
Hi Roelof,

The warning is just to show you that we are unable to determine coverage information. This just means your test session will be slower than it theoretically has to be. This is due to a limitation in xunit I believe. There's nothing to be done about, but it's nothing serious either. It only means we have to run those unit tests for every mutant instead of only for the mutants tested by the tests.

**Comment by RoelofWobben** [comment]
thanks 

any hint how I can do that ?

Roelof

**Comment by dupdob** [comment]
Hi Roelof,
As @Mobrockers said, you do not need to worry about this message. The only downside of this situation is that mutation testing will take longer than necessary. 
# How to remove this
As of now, the only way to get rid of this warning is to avoir using `MemberData` constructions in your tests.
# Why does it happen
To speed up mutation testing phase, Stryker identifies which mutations are tested by which tests. We rely on a custom plug-in for VsTest to capture this information. Sadly,  xUnit's `MemberData` logic does not integrate properly with VsTest, and our plug can't get any reliable information for those tests. Therefore, we need to assume that those tests could be testing any mutants and we end up running more tests than necessary, hence the warning.

We may be able to find a way to improve this, but as of now there is no ongoing effort on this.

I hope this clears things a bit for you. Thanks for your feedback, it is useful. We may consider demoting this message to a lower priority (i.e INFO instead of WARNING) as it appears to be a cause of concerns for users.

**Comment by RoelofWobben** [comment]
Thanks,

to be certain. the outcome of Stryker is good or because this "problems"  the outcome could have some false positives ?

**Comment by Mobrockers** [comment]
@RoelofWobben this as no impact whatsoever on the test result, only on the test speed. Nothing to worry about.

**Comment by RoelofWobben** [comment]
Thanks, then I will close this one or can I better let it open.
For me everythig is clear now so thanks again for the explanation

**Comment by dupdob** [comment]
Thanks. I have added a *Should I worry?* section to my comment for future reference.
