### ISSUE TITLE
Parallel setting

### ISSUE THREAD

**Issue by richardwerkman** [stryker-mutator/stryker-net#111]
The user should be able to define the number of parallel testruns. The default right now is `the number of logical cores / 2`. 

``` 
dotnet stryker --parallel 2 
```

``` json
{
  "stryker-config": {
    "parallel": 2
  }
}
```

We should also explain clearly in the documentation what this setting does. 

The number should be validated to be > 0 and be <= the number of logical cores.

**Comment by nicojs** [comment]
Can we keep it in sync with Stryker? It's called `--maxConcurrentTestRunners` there. The idea is that Stryker still can choose to do other stuff in parallel, so that's why it explicitly states "test runners". Also it's a `max`, so Stryker can choose to use less based on the nr of logical processors. This way it's save to check in a value to source control and you know for sure the configuration will work on machines of team members with less cores. Default value is `infinity`.

**Comment by cmulder** [comment]
I would like to take a look at this :)
