### ISSUE TITLE
Support $(SolutionDir) for dotnet build

### ISSUE THREAD

**Issue by bcollamore** [stryker-mutator/stryker-net#1309]
Projects may reference shared artifacts (e.g., editorconfig, or ruleset, or snk).  Such artifacts can be located from within the .csproj via the Solution root (i.e., $(SolutionDir).  e.g., <AssemblyOriginatorKeyFile>$(SolutionDir)\StrongNameKey.snk</AssemblyOriginatorKeyFile> 

In Stryker, Projects that are not Full-framework build a specific .csproj; in such scenarios, $(SolutionDir) is undefined, so the artifacts are not found, and the build fails. 

**Describe the solution you'd like**
If --solution_path is specified, build the solution rather than a specific project, such that $(SolutionDir) is automatically defined.

**Describe alternatives you've considered**
Pass command-line parameters through to dotnet build (to manually specify $(SolutionDir)

**Additional context**
This request should not adversely affect this enhancement: https://github.com/stryker-mutator/stryker-net/pull/1039

**Comment by mapspiral** [comment]
I concur that this would be a really nice enhancement.

If adding support for this is really as straightforward as updating the InitialBuildProcess.InitialBuild method I'd love to put some time and effort into creating a pull request for this. Since that is basically is what I'm doing to get this to work for our solution :)

**Comment by Mobrockers** [comment]
It should be that straightforward yes.
