### ISSUE TITLE
Coverage analysis doesn't work for solution runs

### ISSUE THREAD

**Issue by richardwerkman** [stryker-mutator/stryker-net#1385]
**Describe the bug**
I've noticed that some mutants are marked as "no coverage" when running from the solution file. While when I run from project file the mutant is marked as "killed". So obviously the coverage analysis doesn't work as expected for soltution runs. It does work partly however. Because most mutants are detected correctly.

**Expected behavior**
I expect the project to have the same coverage when running from both solution and project file.

**Comment by dupdob** [comment]
I had a look at the code and I feel that there is still some work to do on the testing part (for multiple projects).
For example, this [line](https://github.com/stryker-mutator/stryker-net/blob/dcb639a87597c0163319978c53175473f6c0ce7d/src/Stryker.Core/Stryker.Core/CoverageAnalysis/CoverageAnalyser.cs#L38) should be run before running all test projects, and it seems to me it is currently run before running each project.
Hence only the coverage information for the last test project is included.

I may be wrong, because I just add some cursory reading, but I suggest you start from there.
