### ISSUE TITLE
No csproj found when using multiple testprojects option

### ISSUE THREAD

**Issue by rouke-broersma** [stryker-mutator/stryker-net#1387]
The error message in my github actions is blew 
For more, can see it on https://github.com/marsen/Marsen.NetCore.Dojo/runs/1760128678?check_suite_focus=true

 Version: 0.21.1 (beta)

[06:57:56 WRN] Stryker is running in single threaded mode due to max concurrent testrunners being set to 1.
[06:57:56 INF] Identifying project to mutate.
[06:57:56 INF] Time Elapsed 00:00:00.1929827

No .csproj file found, please check your project directory at /home/runner/work/Marsen.NetCore.Dojo/Marsen.NetCore.Dojo

Error: Process completed with exit code 1.

_Originally posted by @marsen in https://github.com/stryker-mutator/stryker-net/discussions/1384_

**Comment by Mobrockers** [comment]
@marsen could you try removing the project file option (-p)? Stryker should automatically find the correct project under test when you set the test projects.

**Comment by marsen** [comment]
Hi @Mobrockers 
Thanks for replay 
I tried some different config settings
the first solution, add the --solution-path(and keep -p option), it worked for me 
sample:https://github.com/marsen/Marsen.NetCore.Dojo/actions/runs/510782012
the other ways are not good enough for me 

the second solution, removing -p 
the result like 
> No .csproj file found, ...
sample:https://github.com/marsen/Marsen.NetCore.Dojo/runs/1766100472?check_suite_focus=true


the 3rd solution I've tried is removing -p and add --solution-path
mean that only --solution-path, it's worked but very wired is the mutation down to 3.05%(original should be over 80% )
sample:https://github.com/marsen/Marsen.NetCore.Dojo/runs/1766125223?check_suite_focus=true

**Comment by D9bolic** [comment]
@marsen  Unfortunately provided workaround doesn't work if the solution file places not in the root(src/bla-bla.sln in my case). Also in that case -p removing and -p removing + solution defining doesn't work too.
From logs it tries to scan the root directory for csproj files:
2021-01-29T22:44:46.0857895+03:00  [VRB] Scanned the directory "D:\Projects\My\D9bolic.Service.Common" for "*.csproj" files: found [] (eedf8c90)

**Comment by D9bolic** [comment]
@rouke-broersma  Hi! Could you provide any updates on this issue? We have really fallen in love with stryker in our project pipeline so want to return it on board.

**Comment by Si1ver** [comment]
Hello.

I have same issue in slightly different project setup. I decided to share my experience and some debugging I've done.

I have solution file in root directory and C# projects in folders
```
D:\Solution\Solution.sln
D:\Solution\Project\Project.csproj
D:\Solution\Project.Tests\Project.Tests.csproj
```

I was using command `dotnet stryker --test-projects "['./Project.Tests/Project.Tests.csproj']"` to run Stryker from the root directory of the project.

The only Stryker version that works for me is `0.20.0`.

Stryker version `0.19.0` fails with error message
```
Stryker could not build your project as no solution file was presented. Please pass the solution path using --solution-path "..\my_solution.sln"
```

Stryker versions from `0.21.0` to `0.22.3` are failing with error message
```
No .csproj file found, please check your project directory at D:\Solution
```

I think that this bug was introduced in change `Multi project runs: Multi project runs using solution file` (#1039).

What happens is in `ProjectOrchestrator.cs` in `MutateProjects` at line 61 the list of test projects are stripped from options when no solution file is present in the options.
`yield return _projectMutator.MutateProject(options.Copy(options.BasePath, null, null), reporters);`
https://github.com/stryker-mutator/stryker-net/pull/1039/files#diff-08cfbceb0a70ed9762b43ccafe4e38b794b263a8eac8d2d80155821ca291451dR61

It's not enough to only leave list of test project in options but also to support this scenario in `InputFileResolver.cs` in `ResolveInput` at line 73 when list of test options is observed.
`if (options.TestProjects != null && options.TestProjects.Any())`
https://github.com/stryker-mutator/stryker-net/pull/1039/files#diff-6c4a8d0e616d17d8b1ecff007db6c5fc09d8007d06cb6b4a78e742d2f1507fa8R73

If one will change line 61 in `ProjectOrchestrator.cs` from
`yield return _projectMutator.MutateProject(options.Copy(options.BasePath, null, null), reporters);`
to
`yield return _projectMutator.MutateProject(options.Copy(options.BasePath, null, options.TestProjects), reporters);`

and line 73 in `InputFileResolver.cs` from
`if (options.TestProjects != null && options.TestProjects.Any())`
to
`if (options.TestProjects != null && options.TestProjects != null && options.TestProjects.Any())`

then one will see that old behavior is working, at leas in my setup.

This fix is only proof of concept. Probably a lot more work have to be done to fix this issue.

**Comment by RaimondB** [comment]
I am seeing the same issue. We have a quite large solution with around 50 projects, half of them being test projects. What I would like to do, is to run stryker using the Solution file, and simply do a run with mutations for each of the test projects.

We are using .NET 5.

As I understand, this shoudl be possible using the above described patterns? I'll try the above fixes and see if this will work.

**Comment by rouke-broersma** [comment]
Hi @RaimondB

Solution runs are an experimental feature. We have found several problems that can cause inconsistent results. Use at your own caution until these problems are fixed.

**Comment by fiegam** [comment]
Hi

I have a similar issue with multiple test projects setup. I'm trying to run stryker from the location where project under test exists, and pass the test projects location as parameter, according to the documentation
[https://stryker-mutator.io/docs/stryker-net/Configuration#test-projects](url)
But seems that the project from current location is considered as test project, and I'm getting error:
> Test project contains more than one project references. Please add the --project-file=[projectname] argument to specify which project to mutate.
Choose one of the following references:

as the project contains more than on project reference.
I tried to use -p <project path>, but got the same result. Also tried v0.20.0 - no luck

I'm using .NET 5.

[log-20210625.txt](https://github.com/stryker-mutator/stryker-net/files/6714870/log-20210625.txt)

**Comment by rouke-broersma** [comment]
Hi @fiegam,

Could you provide us with a description of the filesystem, the project references (redacted) of all test projects and the name (redacted) of the project under test passed to -p?

**Comment by fiegam** [comment]
Thanks for reply,

I've created test solution to reproduce this issue. 
The projects structure looks like this:
ClassLibrary1
ClassLibrary2
ProjectToTest (reference to ClassLibrary1 and 2) <WORKING DIRECTORY>
TestProject (reference to ProjectToTest)

command: dotnet stryker -tp "['../TestProject/TestProject.csproj']" -p ProjectToTest.csproj -f

[StrykerTest.zip](https://github.com/stryker-mutator/stryker-net/files/6716845/StrykerTest.zip)

**Comment by rouke-broersma** [comment]
Hi @fiegam 

Do you in reality only have one test project? If so, this feature is not really for you. You should run stryker from the test project folder if you have one test project.

**Comment by fiegam** [comment]
Hi @rouke-broersma, 
No, this is only for reproduction purposes. In real application I have multiple test projects, and I need to use all of them to cover all functionality from "ProjectToTest". 
I also tried to test the whole solution at once, but this also does not seems to work correctly in my case (I need some more time to investigate and describe those problems)

For other project from th same solution, if the functionality can be covered by single test project, I'm running stryker from test project directory, and it works correctly. I love the report it generates, it is really helpful. It would by wonderful if we could test whole our solution.

**Comment by rouke-broersma** [comment]
Related to #1976
