### ISSUE TITLE
Don't ask users to report rollbacks on known bad constructs

### ISSUE THREAD

**Issue by rouke-broersma** [stryker-mutator/stryker-net#1400]
**Is your feature request related to a problem? Please describe.**
Stryker sometimes places mutations that cause compilation errors. We would avoid that if possible, so we ask users to report rollbacks to us. Users keep reporting the same rollbacks to us, creating more and more issues.

**Describe the solution you'd like**
We should track known faulty mutations and not ask users to report on them. 

**Additional context**
In #933 we decided that it is impossible to never cause compilation errors when mutation while(true) constructs. Therefore we should not ask users to keep reporting this rolled back mutation.

**Comment by dupdob** [comment]
I am not sure we can implement the logic along those lines, i.e. : not reporting when roll backing known problematic constructs. Mostly because it is going to be difficult to identify the bad constructs once we are rollbacking the method, the main problem being that the error messages is reported at some other place.

I would suggest a slightly alternative approach:
**Solution**
- skip mutation of known problematic construct to avoid safe mode an error signaling to the user.

**Comment by Mobrockers** [comment]
@dupdob Ideally we should of course fix the problems our users report asap. But in practice this is not always possible. This feature would be used in between when a user reports an issue and when we have had time to fix the problem, so that we do not keep asking users to report the same issues over and over again.

What I was thinking was that we might detect at creation time that a mutation is a known bad construct and 'tag' it as DoNotNotifyUser or something similar. Of course this would only be used for mutation constructs that are not a quick fix. Perhaps this does not happen often enough to warrant such a feature.

**Comment by dupdob** [comment]
@Mobrockers : thanks for the clarification.
I definitely think we can add a tagging logic so that the warning is not produced on roll back (i.e. do not report if the method contains the 'do not report' tag).
I sill not convinced it is needed because I see little difference between 'tagging' and 'skipping', but this is easy to implement and see if the future proves me wrong 😉.

**Comment by Mobrockers** [comment]
The difference is that we that if we tag and we made a mistake or could not oversee how many different constructs would be affected (ie not actually a faulty mutation) then there won't be a compile error and the mutation will still be applied and tested. If we skip and we made a mistake, the mutation will not be placed in the first place which means missing mutations.

I do doubt myself if this situation would ever exist so perhaps it is not useful at all.

**Comment by dupdob** [comment]
I am still working and coverage and testing redesign (as well as bug fixing along the way) so not started yet on the tagging logic (note that my idea is to simply add a tagging logic to prevent the warning to be displayed, nothing about when to tag).
I reopen the discussion due to issue #1533; it clearly shows we need to improve on the reporting process for those.
I was thinking about either adding a specific issue template (e.g. Safe Mode issue report) or directing people to the discussion board instead, so that discussion could help the best course of action for the problem.

By the way, I have a working fix for #1533: it turns out the error span covers the whole expression, therefore you have to drill down the find the mutation within. Drill down only happens when scanning up (in the syntax tree) failed.

**Comment by rouke-broersma** [comment]
Yes having a new issue template specifically for these kinds of bugs sounds great so we can more easily track them with tags and such.

**Comment by dupdob** [comment]
The report comment has been removed from some time now, so this issue is no longer relevant.
