### ISSUE TITLE
Compile Error: The name 'x' does not exist in the current context

### ISSUE THREAD

**Issue by bcollamore** [stryker-mutator/stryker-net#1423]
Compile Error: The name 'SizeSuffixes' does not exist in the current context

"[08:26:17 WRN] Safe Mode! Stryker will try to continue by rolling back all mutations in method. This should not happen, please report this as an issue on github with the previous error message."

Note:  The run succeeded after rolling back

 - OS: Linux
 - Type of project: Core
 - 3.1
 - Stryker Version: 0.21.1

Hopefully relevant logs attached, as well as original method being mutated:
[StrykerLogs.txt](https://github.com/stryker-mutator/stryker-net/files/6010457/StrykerLogs.txt)

**Comment by Mobrockers** [comment]
Thank you for the reporting!

**Comment by richardwerkman** [comment]
It seems you use a way of array decraration we haven't seen before. We should look into how this is mutated and add some tests for this secific way of declaration:

``` cs
string[] SizeSuffixes = { "bytes", "KB", "MB", "GB", "TB", "PB", "EB", "ZB", "YB" };
```

Thanks for reporting!

**Comment by dupdob** [comment]
Well, this is embarrassing.
The issue is not due to the array declaration syntax, which woks fine. It simply that array declaration used for a variable declarations lead to this kind of issues.
This should have been identified earlier, but unit tests sadly used too simple examples to spot this.
Working on a fix.
