### ISSUE TITLE
TargetPlatform setting for the VS test runner

### ISSUE THREAD

**Issue by laurenceSaes** [stryker-mutator/stryker-net#1425]
**Is your feature request related to a problem? Please describe.**
We are developing a 64 bits only project. When we want to run stryker-net, we have to modify VsTestRunner.cs and add  `<TargetPlatform>x64</TargetPlatform>` to the run setting file. The test runner will fail when we do not specify the target platform.

**Describe the solution you'd like**
Is it possible to add a setting in the stryker configuring where you can specify the TargetPlatform?

**Additional context**
The setting could be added as target-platform into the stryker configuration:

![image](https://user-images.githubusercontent.com/518177/108677991-c6b74180-74ea-11eb-8021-1d5e01d2e07a.png)

**Comment by Mobrockers** [comment]
It is possible and it is a good suggestion. I can't give an estimate on when we'll get around to it unfortunately. I'll try to squeeze it in with #1273

**Comment by richardwerkman** [comment]
Is this information also in your csproj? We could try to get it from there instead of adding a new option to stryker

**Comment by xcap2000** [comment]
> Is this information also in your csproj? We could try to get it from there instead of adding a new option to stryker

I would prefer a new option in stryker if I had to choose, In my case I embed some resources during build according to whether it is x64 or x86 and having this in stryker would be perfect as during build my csproj would take from stryker config as I use the msbuild variable "$(Platform)" in the csproj file.

**Comment by dupdob** [comment]
I am adding support for configuration selection for Stryker. The selected configuration (if any) will be used everywhere; that is from initial build up to mutation testing. This includes running VsTest with the specified target context (framework version and platform). My understanding is that it should implement the feature you need, assuming you have a configuration for x64.
I prefer not to add a specific parameter in order to specify the platform. Indeed, Stryker cannot identify if a project is for a specific platform or as platform specific rules; thus it could result in error during compilation. But I am open to hear your opinion on this a I may be missing something here.
