### ISSUE TITLE
Restore original dlls after run

### ISSUE THREAD

**Issue by sbergen** [stryker-mutator/stryker-net#1515]
**Is your feature request related to a problem? Please describe.**
When running tests in Rider, it will not recompile the main project dlls if there are no changes in the source files. When running Stryker, it will modify the dlls in a way that breaks test runs in Rider. This forces me to recompile the project manually in Rider after running Stryker.

**Describe the solution you'd like**
It would be nice if Stryker restored the original dlls (if present before the run) after the run has finished, or modify them out-of-place.

**Describe alternatives you've considered**
Deleting the modified dlls or recompiling the project would also work, but are slower solutions.

**Comment by rouke-broersma** [comment]
Stryker always performs an initial clean build of the project to make sure the original source is buildable (and any build issues must thus be caused by stryker) so the original dll will always be available after the initial build stage. We should cache the dll just before compilation because just before compilation we have all information we might have needed to extract from the original dll so it's not needed anymore.
