### ISSUE TITLE
Default source branch master/main

### ISSUE THREAD

**Issue by richardwerkman** [stryker-mutator/stryker-net#1545]
**Is your feature request related to a problem? Please describe.**
Currently the default branch for diff/since is `master`. But `main` is also standard now. 

**Describe the solution you'd like**
Stryker should check if master is available as branch. If not it should choose `main` as default branch

**Describe alternatives you've considered**
We can also just switch the default to `main` but this would mean a breaking change

**Additional context**
The default is placed in SinceTargetInput.cs 

This feature is dependent upon #1273

**Comment by rouke-broersma** [comment]
This would bring checking git info into the options. I would prefer to keep this out of there. Users have the capability to change their target branch to main if they use main. I think that's good enough. In some years when the majority use main instead of master we can switch the default to main imo, for now I don't see the point.

**Comment by iamdmitrij** [comment]
I've stumbled upon the same issue. I'm a little confused with which setting can be used as a workaround to switch branch. Is it `since.target`, `project-info.version` or something else?

**Comment by rouke-broersma** [comment]
> I've stumbled upon the same issue. I'm a little confused with which setting can be used as a workaround to switch branch. Is it `since.target`, `project-info.version` or something else?

since.target is the option for the branch you want to diff against.
