### ISSUE TITLE
Compiler Error is Caused With `^` in Code

### ISSUE THREAD

**Issue by JasonBock** [stryker-mutator/stryker-net#1605]
**Describe the bug**
When I run Stryker on my code (which can be found [here](https://github.com/JasonBock/SpackleNet/blob/main/Spackle/SecureRandom.cs#L158)), it tries to replace `^` with `==`, and in this case, that's incorrect.

**Expected behavior**
Stryker runs without generating a compiler error.

**Desktop (please complete the following information):**
 - OS: Windows
 - Type of project: .NET 5.0
 - Stryker Version: 0.22.4

**Comment by rouke-broersma** [comment]
This is a known bad mutation that is a consequence of not having type information available. This mutation is valid for bool but not byte (I believe). We should not warn for this.

#1400

**Comment by dupdob** [comment]
It turns out this by design; see issue #664 for reference : Stryker deliberately injects both a logical AND an (bitwise) arithmetic mutation, knowing one of them will be removed.

But my understanding is that this error is properly removed and does not trigger a local rollback. If this is the case, this should not be viewed as an issue.

**Comment by JasonBock** [comment]
I haven't looked at the implementation of Stryker, but, if you're using the Compiler API to analyze the code under test, it might be possible to determine if the two nodes of an `ExclusiveOrExpressionSyntax` are targeting boolean or integral numeric values.

**Comment by dupdob** [comment]
In order to keep the mutator code base simple andStryker fast, the mutation philosophy is:
1) work with the syntax tree and not the semantic model; the semantic model is slower to get and requires solving dependencies
2) for each error, remove related mutations.

Note that (2) is required because:
1) experience has taught us that some mutators can lead to unpredictable errors with some constructions (`while(true)` for example)
2) we can keep mutators code very simple by not trying to detect if they may trigger an error.

Ultimately, this is (almost) an implementation detail. The only byproduct is the generation of mutant in _CompileError_ state, without any impact on the overall experience. Alternatively, they could be silently removed, but we think it is better to track them.

Do you feel there is an issue or concern we are not seeing here?

**Comment by JasonBock** [comment]
I understand the point about the semantic model that it does add some overhead. For the `ExclusiveOrExpressionSyntax` node case, is it more expensive to get the semantic model in play and determine if a mutation is valid, or simply make the mutation and see that the compiler has an error? I don't know, I'm assuming that's perf work you've already done.

**Comment by rouke-broersma** [comment]
I have not personally ran the perf work (@richardwerkman has but not specifically for this case) but Roslyn is so blazing fast at compiling, and remove a bad mutation is so 'trivial', that I am easily willing to bet it will be way way way faster than using the semantic model.

**Comment by JasonBock** [comment]
I wouldn't argue that bet. But with anything perf-related, it's always good to get the numbers.

But here's another thought. In the case that I presented, the code is doing `^` on two `NumericLiteralExpressionSyntax` nodes. Would it be possible to do a look at the nodes being used for `ExclusiveOrExpressionSyntax`, and for the simple cases you can run into (e.g. it's using `NumericLiteralExpressionSyntax` or `FalseLiteralExpressionSyntax`), you can determine which mutator to use. For other cases where something like an `InvocationExpressionSyntax` or `IdentifierNameSyntax` is in play, you can't, so you'll still have to do both mutations for `^`.

**Comment by rouke-broersma** [comment]
That would be a good improvement!
