### ISSUE TITLE
Fixing Test Does Not Remove Mutant

### ISSUE THREAD

**Issue by JasonBock** [stryker-mutator/stryker-net#1606]
**Describe the bug**
Stryker reported a mutant that wasn't killed:
![image](https://user-images.githubusercontent.com/904213/122973013-60d2ad80-d356-11eb-861d-6df5f11a325c.png)
So I changed the test, but the mutant doesn't go away. You can check out the branch [here](https://github.com/JasonBock/Transpire/tree/4_add_stryker). The test is `FindNewGuidViaConstructorAnalyzerTests.VerifySupportedDiagnostics()`. Before, I didn't verify `IsEnabledByDefault`, so then I added an assertion, but subsequent Stryker runs still report the surviving mutant. If I change the `true` value to `false`, the test will fail as expected.

**Desktop (please complete the following information):**
 - OS: Windows
 - Framework Version: .NET 5.0
 - Stryker Version: 0.22.5

**Comment by dupdob** [comment]
Thanks.
# Explanation
This typically happens when some tests are not completely isolated, which results in incorrect coverage information. I have traced the code, and in this instance the problem is that the tested `FindNewGuidViaConstructorDescriptor` is stored in a [static field](https://github.com/JasonBock/Transpire/blob/ad844b4e57e285ca0470fecb6f6e5c670f5d70ac/src/Transpire/FindNewGuidViaConstructorAnalyzer.cs#L15). In short, here is what happens:
1. the constructor is only called once during a test session, even if the instance is used across several tests.
2. when Stryker capture mutation coverage data, it identifies only one (1) test as covering any mutations that are part of the constructor. This is whichever test happens to be the first to use the `FindNewGuidViaConstructorAnalyzer`.
3. then Stryker tests the mutations (inside the class constructor) only against this test, leading to potential false 'survivor'
# How to fix
1. The best approach is to ensure tests are really isolated (against each other). Here I would recommend adding some logic to make sure `VerifySupportedDiagnostics` really tests a newly created `FindNewGuidViaConstructorDescriptor` instance. 
2. Simplest workaround: you can also disable coverage analysis, as such, each mutant will be tested against every tests and the mutant will be killed. Since the project appears small, this should not be an issue, but in the long run, mutation testing may be very long (think hours).
# What about a fix in Stryker?
First of all, let me restate that this situation is the sign of flaw in the test base, not in Stryker. But since, this is a frequent flaw, Stryker integrates detection and mutation marking logic for similar situations. We call those problematic mutations _static mutations_ and we mark them either during mutation phase or the initial test run.
We try and improve this logic when new patterns appear. You can check issues: #949, #623, #1171, #1548. 
But, the workaround implies testing each of those mutations in a dedicated test session against all existing tests, which impairs performance for obvious reasons. Furthermore, we know some patterns cannot be detected, such as static value cache, that is why we recommend making sure tests are fully isolated, which is an hygienic approach.

# What about this specific situation
I think I can provide a marking logic for this construct, but it will probably be delivered as part of the upcoming V1 release, and not as a bug fix for the current version, which should happen in the coming months, weeks at best.
