### ISSUE TITLE
Error During Analysis

### ISSUE THREAD

**Issue by JasonBock** [stryker-mutator/stryker-net#1608]
**Describe the bug**
I ran Stryker against [this code base](https://github.com/JasonBock/wsharp), and during the analysis, this showed up in the logs:
```
[08:48:59 WRN] Stryker.NET encountered an compile error in C:\Users\jason\source\repos\WSharp\WSharp.Compiler\Syntax\SyntaxTree.cs (at 87:72) with message: 'ParseTokens(SyntaxTree)': not all code paths return a value (Source code: (CompilationUnitSyntax root, ImmutableArray<Diagnostic> diagnostics) ParseTokens(SyntaxTree tree)
                        {
                                var lexer = new Lexer(tree);

                                while ((Stryker75poqjYc5xaE43c.MutantControl.IsActive(696)?!(true):(Stryker75poqjYc5xaE43c.MutantControl.IsActive(695)?false:true)))
                                {
                                        var token = lexer.Lex();

                                        if ((Stryker75poqjYc5xaE43c.MutantControl.IsActive(698)?!(token.Kind != SyntaxKind.EndOfFileToken || includeEndOfFile):(Stryker75poqjYc5xaE43c.MutantControl.IsActive(697)?token.Kind != SyntaxKind.EndOfFileToken && includeEndOfFile:(Stryker75poqjYc5xaE43c.MutantControl.IsActive(699)?token.Kind == SyntaxKind.EndOfFileToken :token.Kind != SyntaxKind.EndOfFileToken )|| includeEndOfFile)))
                                        {
                                                tokens.Add(token);
                                        }

                                        if ((Stryker75poqjYc5xaE43c.MutantControl.IsActive(700)?token.Kind != SyntaxKind.EndOfFileToken:token.Kind == SyntaxKind.EndOfFileToken))
                                        {
                                                return (new CompilationUnitSyntax(tree, new LineStatementsSyntax(tree, new List<LineStatementSyntax>()), token),
                                                        lexer.Diagnostics.ToImmutableArray());
                                        }
                                }
                        })
[08:48:59 WRN] Safe Mode! Stryker will try to continue by rolling back all mutations in method. This should not happen, please report this as an issue on github with the previous error message.
```
I'm reporting it because it asked me to :)

**Desktop (please complete the following information):**
 - OS: Windows
 - Framework Version: .NET 5
 - Stryker Version [e.g. beta 0.22.5]

**Comment by dupdob** [comment]
Thanks for reporting this! 
## Error message explanation
Safe mode triggers when Stryker cannot identify which mutation(s) resulted in compilation errors. All mutations are then removed from the method to ensure Stryker can go complete the testing session.

The impact of the safe mode is that some mutations are lost in the process. So this is not a problem per se, just a sub par situation.

## Workaround
No workaround is needed, but you need to somewhat modify the code if you want this method to be part of the mutation testing process (until a proper a fix is released).
Here you can:
- add a `return default;` at the end of the local function
- OR promote the local function to a full formed (private) method if possible

## Cause of the problem
`while(true)` pattern allows to have (non void) methods without an ending `return`. But, when Stryker mutates `while(true)` to `while(false)` (or similar transformations), the method can no longer compile. As a precaution, Stryker injects a `return default;` statement when a (non void) method does not end with a `return` statement.
It turns out this logic needs to explicitly extended to cover local functions.

## Fix
This is NOT a pressing issue, the fix will be integrated in the upcoming V1.
