### ISSUE TITLE
Cannot specify full method name within ignored methods

### ISSUE THREAD

**Issue by psfinaki** [stryker-mutator/stryker-net#1630]
**Describe the bug**

So imagine I have the following code:
```csharp
public static void CheckAnswer(int number)
{
    if (number == 42)
    {
        return;
    }

    CrashWithException("wrong answer");
}

private static void CrashWithException(string text)
{
    throw new Exception(text);
}
```

For `dotnet stryker`, Stryker produces two mutations here, as expected:

![image](https://user-images.githubusercontent.com/5451366/126636289-da492741-3de4-402d-8736-ba98d075e42e.png)

Now I want to ignore the exception text mutation. I run Stryker like `dotnet stryker -im "['CrashWithException']"`.

This also works as expected:

![image](https://user-images.githubusercontent.com/5451366/126643318-708360ff-fc28-4b54-8643-575c1bb304d8.png)

Now I decide to move the `CrashWithException` logic to a separate class `Crash` with the method `WithException`:
```csharp
public static void CheckAnswer(int number)
{
    if (number == 42)
    {
        return;
    }

    Crash.WithException("wrong answer");
}
```
But now if I run it like `dotnet stryker -im "['Crash.WithException']"` the mutation is not ignored anymore:

![image](https://user-images.githubusercontent.com/5451366/126643847-3da05a05-e69d-4dbb-8abb-7cddf3f20ed8.png)

I can ignore just `WithException` but I don't want that - because the name is not generic enough and I'm afraid to miss some important mutations elsewhere in the code. I want to ignore only this particular one in that particular class.

**Expected behavior**
One can specify the full method name within ignored methods setting and this is taken into account.

**Desktop (please complete the following information):**
 - OS: Windows
 - Type of project: Core
 - Framework Version: NET 5.0
 - Stryker Version: 0.22.7

**Additional context**
I attach the repro.
[IgnoreRepro.zip](https://github.com/stryker-mutator/stryker-net/files/6862416/IgnoreRepro.zip)

**Comment by richardwerkman** [comment]
I think we might run into some weird situation as we have to look at the whole `SimpleMemberAccessExpression` for this. Those can contain class names when static, or variable names or even namespaces or namespace aliasses. So that could potentially cause some unexpected behaviour. For example your class could have a property called Crash and if that object has this method if would be ignored as well. But that's a small chance so I think this works fine.

I think we have to look at the end of the expression string to see if the method call should be ignored. As namespaces can always be fully qualified.

**Comment by richardwerkman** [comment]
No in C#. For your example:
```cs
Crash.WithException("wrong answer");
```
could also be written as
```cs
IgnoreRepro.Crash.WithException("wrong answer");
```
So if we check for the full string of the call we might miss some method invocations to ignore

**Comment by psfinaki** [comment]
Oh right, I see. Yeah, fair point. So you think we can do that end string check?

**Comment by richardwerkman** [comment]
Sure, should be no problem 👍

**Comment by psfinaki** [comment]
@richardwerkman do you plan to take it? If not, maybe you could point out to the place where to fix that or so?

**Comment by richardwerkman** [comment]
@psfinaki I don't have time to look into this. But I think I can help you get started.

You have to change to following line to fix this: https://github.com/stryker-mutator/stryker-net/blob/ef16398589a2e34733652b97d84dc05dd106ef51/src/Stryker.Core/Stryker.Core/MutantFilters/IgnoredMethodMutantFilter.cs#L36

As you can see we currently only match the member name to the regex. This should be the complete line for this to work. The end of string check we can implement using the regex maybe? Just input `*WithException` and that should work. 

I think we can just use `invocation.ToString()` to get the complete string of the node. So we won't need to check if the invocation is a `MemberAccessExpressionSyntax` or `MemberBindingExpressionSyntax`. Just toString the invocation and match the regex.

But there is more. We currently use a recursive method to see if any parent node matches the regex. But if we don't change that recursiveness we will match the regex to the complete file when checking the last parent. So that would result in all mutants being ignored if one method matches in the file. So we need extra tests for that. But I think we can easily solve this by limiting the recursiveness till a statement is found. This should have been done with the initial implementation now that I look at it more carefully.

If you have more questions feel free to ask!

**Comment by psfinaki** [comment]
@richardwerkman 
Thank you very much for the info! Expect a PR on that next week :)

**Comment by richardwerkman** [comment]
Awesome! Good luck. 

And a tip: if you want to quickly check how a syntaxtree for this looks like use this website [sharplab.io](https://sharplab.io/#v2:C4LghgzsA0AmIGoA+ABADAAhQRgHQBkBLAOwEcBuAWACh0tsAWK6mlAZiwCYMBhDAbxoZhWDigYYAsgAoAlAKEilANzAAnDABtCUDAF4MxAKYB3DESgAeHGgB8c5kqXaouAOoALI2qPSAHvq2GAF6BgBEJmoA9sQA5hhgxBAm3mGyuAAqURbADorCAL40BUA)

**Comment by psfinaki** [comment]
Also, @richardwerkman, shall I close this already? I understood there are some procedures about the tickets here so I better ask :)

**Comment by rouke-broersma** [comment]
Right sorry it should have been closed with the merge but because we changed the default branch github won't auto close.

**Comment by psfinaki** [comment]
That's alright, watching the issue close is anyway more pleasant than watching it open :D

Thanks! Looking forward to this being released - I guess with that we'll finally have the Stryker configuration we want :)
