### ISSUE TITLE
Static code analysis

### ISSUE THREAD

**Issue by simondel** [stryker-mutator/stryker-net#164]
SonarCloud has an (supposedly) easy to use integration with Azure Pipelines. This could help us identify code smells and potential bugs.

**Comment by ptoonen** [comment]
@simondel are you still actively working on this, otherwise I can pick it up from here?

**Comment by simondel** [comment]
@ptoonen go ahead! I ran into issues SonarCloud. It only parsed code from one project as being C# code.

There is a task based (not YAML) pipeline on Azure Pipelines with SonarCloud. I think it's called `stryker-net OLD` or something.

**Comment by simondel** [comment]
The current project can be found here: https://sonarcloud.io/dashboard?id=stryker-net.stryker-net 

As you can see, SonarCloud only detected 115 lines of C# code. None from the Core package.

The code is there though: https://sonarcloud.io/component_measures?id=stryker-net.stryker-net&metric=lines&selected=stryker-net.stryker-net%3Asrc%2FStryker.Core%2FStryker.Core%2FTesting%2FProcessExtensions.cs

**Comment by ptoonen** [comment]
@simondel can you authorize me on the sonar project?

**Comment by ptoonen** [comment]
Okay, so I can successfully analyze the solutions 1-by-1. The problem is that SonarQube doesn't like code that's referenced by multiple projects (it does correctly mark the files as 'shared' but won't analyze them for some reason). I'm guessing the real problem is that Core and Core.UnitTest are referenced by two solutions in the repository.

Now the solution here is a bit tougher but we've got a few options:

1. Split the repo into multiple repo's - one for core, one for CLI (kind of like the javascript version). This wouldn't be a strange option considering the fact that they're actually two separate things and you may want to version treat them as such.
2. Combine all projects into one solution. Also a valid option because of the tight coupling between them at the moment. This is seems to be the approach sonarsource uses with the msbuild scanner.
3. Build the csproj's rather than the solutions. This is also what happens in the newer azure-pipelines.yml file. This would however mean that we'd need to add a <ProjectGuid> to all the csproj files we would want to analyze otherwise SonarQube doesn't support it.

@richardwerkman @Mobrockers @simondel what are your thoughts on this? Do you see any other viable options?

**Comment by ptoonen** [comment]
ps. I prefer #2

**Comment by simondel** [comment]
@ptoonen I'm not sure if solution 2 would work. There is already a solution that contains all projects. It's the CLI solution.

PS I've granted you and @Mobrockers permissions on SonarCloud (github login). I couldn't rant @richardwerkman any permissions since he never signed in.

**Comment by richardwerkman** [comment]
@ptoonen I'm also in for option 2. However I split the integrationtest project in a new solution intentionally to make live unit testing possible in the CLI solution. Otherwise each line that changes would trigger a 45 second testrun.

**Comment by ptoonen** [comment]
> However I split the integrationtest project in a new solution intentionally to make live unit testing possible in the CLI solution. 

We could keep them separate, or exclude them from live unit testing: https://docs.microsoft.com/en-us/visualstudio/test/live-unit-testing?view=vs-2017#include-and-exclude-test-projects-and-test-methods

**Comment by Mobrockers** [comment]
There is no actual used code in the integration test projects so I suggest we just keep them as it is and not include in sonar analysis

**Comment by ptoonen** [comment]
Okay, so I've got most of it done. Biggest issue we have now is that Sonar will only accept one .trx file. That means we either have to merge, or pick which one we want to use.
 
For the work in progress, look here: https://github.com/ptoonen/stryker-net/blob/164-static-code-analysis/azure-pipelines.yml
