### ISSUE TITLE
[1.0.0-rc2] --project-file becomes --project

### ISSUE THREAD

**Issue by corentinaltepe** [stryker-mutator/stryker-net#1686]
**Describe the bug**
Hello. When I run stryker on a test project pointing to several `*.csproj`, the command line says `Test project contains more than one project reference` and gives an example: `Example: --project-file=C:\Users\altepe\source\repos\[Redacted].csproj`.

However, running the command line with option `--project-file` fails because it has been updated to `--project` in v1.

**Logs**
```
PS C:\Users\altepe\source\repos\[Redacted].Tests> dotnet stryker
Version: 1.0.0
[11:25:43 INF] Identifying project to mutate.
[11:27:34 INF] Time Elapsed 00:01:50.7980044

Project reference issue.

Test project contains more than one project reference. Please set the project option (https://stryker-mutator.io/docs/stryker-net/configuration#project-file-name) to specify which project to mutate.
Choose one of the following references:

  C:\Users\altepe\source\repos\[Redacted].csproj
  C:\Users\altepe\source\repos\[Redacted].cli.csproj

Example: --project-file=C:\Users\altepe\source\repos\[Redacted].csproj
```

**Expected behavior**
I'd like to propose two options:
1. Update documentation and command line error messages to `--project` instead of currently `--project-file`. I would favor this one. It will impact a very few lines of code. Though this would go against https://github.com/stryker-mutator/stryker-net/issues/142 and https://github.com/stryker-mutator/stryker-net/pull/129.
2. Update command line option to set it back to `--project-file` instead of the currently supported `--project`.

Which one would you recommend?

**Comment by philrowan-mtb** [comment]
That link https://stryker-mutator.io/docs/stryker-net/configuration#project-file-name does not exist in the current beta but actually will be fine with the 1.0.0 docs since the configuration page is updated (see https://github.com/stryker-mutator/stryker-net/blob/v1.0/docs/configuration.md#project-file-name). However, I do think that `#project` would be a nicer link. If the type info were moved into the section those links would be more nice I think. It could also be a chance to address what appears to be some inconsistency where some headings have usage info and some have type info inside the angle brackets. For example

### `project` <`file-name`>

Default: `null`  
Command line: `[-p|--project] "MyAwesomeProject.csproj"`  
Config file: `"project": 'MyAwesomeProject.csproj'`

The project file name is required when your test project has more than one project reference. Stryker can currently mutate one project under test for 1..N test projects but not 1..N projects under test for one test project.

*\* Do not pass a path to this option. Pass the project file **name** as it appears in your test project's references.*

### `test-projects` <`string[]`>

Default: `null`  
Command line: `N/A`  
Config file: `"test-projects": ['../MyProject.UnitTests/MyProject.UnitTests.csproj', '../MyProject.SpecFlow/MyProject.SpecFlow.csproj']`

When you have multiple test projects covering one project under test you may specify all relevant test projects in the config file. You must run stryker from the project under test instead of the test project directory when using multiple test projects.


would become


### `project`

Type: `string`
Default: `null`  
Command line: `[-p|--project] "MyAwesomeProject.csproj"`  
Config file: `"project": 'MyAwesomeProject.csproj'`

The project file name is required when your test project has more than one project reference. Stryker can currently mutate one project under test for 1..N test projects but not 1..N projects under test for one test project.

*\* Do not pass a path to this option. Pass the project file **name** as it appears in your test project's references.*

### `test-projects`

Type: `string[]`
Default: `null`  
Command line: `N/A`  
Config file: `"test-projects": ['../MyProject.UnitTests/MyProject.UnitTests.csproj', '../MyProject.SpecFlow/MyProject.SpecFlow.csproj']`

When you have multiple test projects covering one project under test you may specify all relevant test projects in the config file. You must run stryker from the project under test instead of the test project directory when using multiple test projects.

**Comment by corentinaltepe** [comment]
Thank you @philrowan-mtb. My assumption about markdown links was wrong, and the link was correct. So I did not modify it.

I agree with your proposition to restructure documentation. It would offer better clarity. Should we go for it? We'd have to search for all links to the doc to update them.

**Comment by rouke-broersma** [comment]
The configuration docs are modeled after the [stryker-js](https://stryker-mutator.io/docs/stryker-js/configuration) and the [stryker4s](https://stryker-mutator.io/docs/stryker4s/configuration) docs to bring them more in line with eachother. I used `<>` instead of `[]` because in my experience `[]` usually means optional argument and is also used for options that accept multiple arguments so I found that to be confusing. 

I do agree that there is some inconsistency in the usage example given, afaik mostly on array or boolean types, but I would not go so far as to diverge from the other docs again when this was an attempt to get more in line with the rest.

Let's start a discussion here: https://github.com/stryker-mutator/stryker-mutator.github.io/discussions
That way all stryker projects can weigh in on how the configuration pages should look.
