### ISSUE TITLE
Incorrect CLI message when updating Stryker to 1.0.0

### ISSUE THREAD

**Issue by psfinaki** [stryker-mutator/stryker-net#1761]
**Describe the bug**
First, one picture instead of a thousand words:

![image](https://user-images.githubusercontent.com/5451366/139659336-4299aa42-fe88-4d3a-846e-b95804c83884.png)

Hopefully you can see things despite my amazing skills of sticking to the company's NDA :D 

I tried different ways: updating the tool directly, uninstalling + installing with the version specified, uninstalling + installing without the version specified - same output. 

**Expected behavior**
Smooth update - no message, no "undefined" suffix in the version.

**Comment by psfinaki** [comment]
Can reproduce locally from the master:
![image](https://user-images.githubusercontent.com/5451366/139660950-6063a958-4ba9-48a8-8e18-53abaf4c8d28.png)

**Comment by rouke-broersma** [comment]
This appears to be by design 😇 

https://github.com/stryker-mutator/stryker-net/blob/42d3b4b31e6722d5d8dd2fd76e6d90da4e36bad5/src/Stryker.CLI/Stryker.CLI/Stryker.CLI.csproj#L14
https://github.com/stryker-mutator/stryker-net/blob/42d3b4b31e6722d5d8dd2fd76e6d90da4e36bad5/package.json#L4

@richardwerkman I think we have a bug in our nodejs script causing a variable to be undefined for the version suffix

**Comment by rouke-broersma** [comment]
It also probably causes the preview version message to print

**Comment by richardwerkman** [comment]
Huh, I thought I tested that as well. But this is indeed incorrect. I'll take a look at this tonight
