### ISSUE TITLE
Minor: block mutations are not formatted correctly in the reports

### ISSUE THREAD

**Issue by psfinaki** [stryker-mutator/stryker-net#1775]
**Describe the bug**
Not sure if this is the right place for the bug but here's the thing:
![image](https://user-images.githubusercontent.com/5451366/139918700-3e42ffc2-e08f-4a34-b7fe-a4db620f0e9c.png)

**Expected behavior**
There should be a space there :)

**Comment by rouke-broersma** [comment]
Could you show what the json report looks like for this node? Then we can determine if this is a problem with the display or with the actual mutant generation.

**Comment by rouke-broersma** [comment]
How does that compile 😂

**Comment by richardwerkman** [comment]
We compile straigt from the AST. So if the AST is correct but missing trivia it will compile. But yeah this looks bad indeed

**Comment by richardwerkman** [comment]
![image](https://user-images.githubusercontent.com/14224500/150506234-a3f7a20b-c55f-4970-a497-13ca766c932a.png)

I think this issue is no more. The return default is no longer contained in the mutation itself. It's now placed afterwards by a mutationEngine. So it now looks like above. I'm closing this issue
