### ISSUE TITLE
Add DateTime mutator

### ISSUE THREAD

**Issue by broodjetom** [stryker-mutator/stryker-net#211]
Add a mutator for DateTime.

During test, using 'Now' to get current week number. Check for the weeknumber in an Assert. Week later, the test didn't work anymore.

**Comment by richardwerkman** [comment]
Interesting! How would this look? Because we will not know what the perpose of the datetime will be. It could be to get the day of the week or to get the hour. 

For example a test that checks a method to see if it is monday. If we would mutate a date to be a week in the future, the test would still see that the date would be monday. But the test was correct. I guess we have to think real good before we define a mutator like this.

**Comment by broodjetom** [comment]
So I was making some tool to search results by weeknumber. And I made a wrong unit test. I was testing it by using DateTime.Now as input for an extension method to calculate the weeknumber by date:

```
var date = DateTime.Now;
var week = date.GetWeekNumber();
Assert.AreEqual(41, week);
```

This test was passing because I made this in week 41. One week later this test was failing simply because it wasn't the 41st week anymore.

I think with this can be mutated DateTime.Now with some random date, or adding extra years, months, days, hours, and/or minutes.

**Comment by ptoonen** [comment]
Hi @broodjetom I was looking at this issue but I think I'm missing something. In your example it seems as though you're testing framework code rather than your own. Although we would technically be able to alter your tests, that's not really the purpose.

Could you maybe elaborate on the use case?

**Comment by Mobrockers** [comment]
@broodjetom I'm closing this issue for now. If this becomes relevant for you again please answer the above question and we'll take a look.
