### ISSUE TITLE
Baseline Compare - issue with older sv (signed version) SAS token AzureStorageProvider

### ISSUE THREAD

**Issue by LiamCottrell** [stryker-mutator/stryker-net#2114]
**Describe the bug**
Using Baseline compare with the AzureFileStorage provider, the SAS token `azure-fileshare-sas` seems to specifically need a newer version than we are using, `2017-07-29` as stryker seems to append http headers that are not supported by this and other older versions.

**Logs**
For us to best assist you in diagnosing the problem we would ask you to run stryker with the option `--log-to-file` or `-L` and to attach the resulting logs to the issue.

```
2022-07-22T10:21:24.4543386+01:00  [DBG] "feature/20167-baseline-functionality-in-Stryker-pipelines" identified as current branch (5a224eb9)
2022-07-22T10:21:24.6449067+01:00  [DBG] Allocating storage for file "https://mystorage.file.core.windows.net/azdo-pipelines/StrykerOutput/TestProject.TestAPI.Tests/baseline/feature/20167-baseline-functionality-in-Stryker-pipelines/stryker-report.json" (503a83a4)
2022-07-22T10:21:24.6678812+01:00  [ERR] Azure File Storage allocation failed with statuscode "BadRequest" and message: "<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>UnsupportedHeader</Code><Message>One of the HTTP headers specified in the request is not supported.
RequestId:c2331186-201a-0005-27ac-9d63c1000000
Time:2022-07-22T09:21:22.3288941Z</Message><HeaderName>x-ms-file-permission</HeaderName></Error>" (97ca4f7e)
```

**Expected behavior**
Either conditional stripping of non supported http headers is performed when sas token with older version is provided, or documentation detailing what version of api is targeted to give clear instruction for users to target sas token generation.

**Desktop (please complete the following information):**

- OS: [e.g. Windows] Windows
- Type of project [framework, core, xamarin] Core
- Framework Version [e.g. core 2.2] core .net6
- Stryker Version [e.g. beta 0.10.0] 2.0.0

**Additional context**
https://docs.microsoft.com/en-us/rest/api/storageservices/version-2021-06-08
Earliest version that i can see where new headers that stryker is appending to requests to azure file storage seem to be present.

I am using terraform to be able to provision SAS tokens, and there is currently an open issue with the terraform azurerm provider where by attempting to generate a newer version of sas token is currently broken.
https://github.com/hashicorp/terraform-provider-azurerm/issues/17558

**Comment by rouke-broersma** [comment]
According to the docs you are almost correct. The docs for `x-ms-file-permission` specify:

```
In version 2019-02-02 through 2021-04-10, this header is required if x-ms-file-permission-key isn't specified. As of version 2021-06-08, both headers are optional.
```

This header was required when baseline was first implemented. It seems that by now the header has been made optional. We do not rely on this header, it has only been added because it was required in the past. The header can be removed if this does not affect azure baseline functionality.

Would you be in a position to try this out and submit a PR for the change?

Any other headers that have been made optional may also be removed. For example `x-ms-file-attributes` and `x-ms-file-last-write-time`.

It would also be great to pin an api version so we don't run into such issues in the future.
