### ISSUE TITLE
string concatenation with "+" must not be changed to "-" because of compile error

### ISSUE THREAD

**Issue by slieser** [stryker-mutator/stryker-net#2125]
**Describe the bug**
Stryker changes plus signs "+" in expressions to minus "-". It does it even on string expressions but the resulting code will not compile.

var s = "aaa" + "bbb";

will change to 

var s = "aaa" - "bbb";

That won't compile.

**Expected behavior**
Don't change "+" to "-" in string expressions.

**Comment by dupdob** [comment]
Thanks for your concern and reporting this, but this issue lacks details, more specificialy: is this is a problem for you ? if yes how/why?
One of the Stryker's main design principles is that it generates a maximum of mutations and then removes the ones causing compilation errors. So we do not expect binary operations on strings to be an issue with mutations.
More specifically, there is a detection logic in Stryker so that it does not mutate binary operations when literal strings are present. This means that `var s = "aaa" + "bbb";` will NOT be mutated `var s = "aaa" - "bbb";`.

if you encounter this situation, could you please provide a reproduction example?

**Comment by slieser** [comment]
Ok it was not on two literals but on a variables or parameters:

public class Concatenator
{
    public static string Concat(string a) {
        var b = "bbb";
        return a + b;
    }
}

Now I understand that there will always be compile errors. You ignore them and that's it?

**Comment by rouke-broersma** [comment]
Pretty much. We will at some point try to limit compilation errors where we can, but since we have a very robust mechanism to deal with compilation errors it is imo not worth our time at this point to deal with it.

**Comment by slieser** [comment]
I understand. So thanks for your great work!
