### ISSUE TITLE
Stryker explodes for locks

### ISSUE THREAD

**Issue by psfinaki** [stryker-mutator/stryker-net#2249]
**Describe the bug**
Looks like I've found a good old code-related bug :)

Basically this code:
```csharp
public class SomeClass
{
    private readonly List<int>? _numbersBeforeCtor = new();
    private readonly object _lockObj = new();

    public SomeClass()
    {
        List<int>? numbers;
        lock (_lockObj)
        {
            numbers = _numbersBeforeCtor;
        }

        if (numbers is not null)
        {
        }
    }
}
```
causes Stryker to panic:
![image](https://user-images.githubusercontent.com/5451366/197214686-2f931196-7ff4-48cf-9062-5138ac119b49.png)

**Expected behavior**
This code compiles - so smooth execution, no errors.

**Desktop (please complete the following information):**
 - OS: Windows
 - Type of project: .NET Core
 - Framework Version: .NET 6
 - Stryker Version: 3.0.1
 
**Additional context**
Repro is here: [Repro.zip](https://github.com/stryker-mutator/stryker-net/files/9839698/Repro.zip)
I don't think it's a regression - we have quite an old Stryker version in the pipeline and there is also seems to be the case.

Also, the code in question is useless - because, well, all the business logic is removed due to NDA :D But hopefully that's enough.

**Comment by dupdob** [comment]
yep, there is at least one bug: safe mode should succeed. This is surprising, because, there is an internal error if rollback fails, normally....

**Comment by dupdob** [comment]
## Analysis
Mutations on this code will often result in a 'use of un initialized variables (numbers) error'. This error is reported at the first attempt to use the variable, which is not related to the mutations that triggered it.
When this happens, Stryker attempts to recover rollbacking all mutations in the enclosing method.
Here Stryker fails to find the enclosing method because this is a constructor (not a method). Long story short, Stryker tries several times to remove mutations where there are none, which obviously will never fix the initial problem.

## Workaround
The short term workaround is to disable block and statements mutations on constructors triggering this (via Stryker comments). This comments should be removed when the fix will be released

## Fix
The main issue (finding the enclosing method even if it is a constructor) is easy to fix. But I am working on improving the fail safe strategy to ensure this does not happen for another kind of syntax construct.

**Comment by rouke-broersma** [comment]
Stryker comments won't fix this problem because we still place the mutation, only set it to ignored, right?

**Comment by dupdob** [comment]
Yes, thanks. Fixed my comment

**Comment by rouke-broersma** [comment]
Once #2250 is release this error should no longer be blocking, however you might lose mutant information about other mutants in a constructor because in this case we cannot properly find the offending mutant and rollback everything in the constructor. Right, @dupdob ?

**Comment by psfinaki** [comment]
Hmm well now it doesn't explode but I guess still doesn't work correctly:
<img width="945" alt="image" src="https://user-images.githubusercontent.com/5451366/197545756-0a2f6e6e-ed80-437a-a7fa-1e152fe7372a.png">

**Comment by dupdob** [comment]
At least it works as expected; that it runs correctly is another topic. As of now, Stryker.Net does not mutate patterns, so it can not mutate `if (numbers is not null`. There is no expression to mutate, and no allowable statement to mutate (statement mutator skips flow control statements and assignments). Only the block mutator can mutate the existing two blocks (the `lock` and constructor body blocks). 

Alas, since mutating `{ numbers = _numbersBeforeCtor; }` to an empty block triggers a compilation error, it results in all block mutations being removed as part of safe mode. Hence you have two mutations flagged as compilation errors.
Without adding new mutators, the best we could hope for is having one correct mutation: the whole constructor's body being mutated to an empty block.

Issue #1953 is opened to track progress on reducing the compilation errors due to block mutations.

@rouke-broersma: not sure what you mean. Safe mode will function properly for constructor as well. So when an orphan compilation error happens in a constructor, all block mutations will be removed flagged as compilation error, exactly like it happens today in methods, function and accessors.

**Comment by psfinaki** [comment]
This can be probably closed now?
