### ISSUE TITLE
html vs cleartext reporters give differing stats

### ISSUE THREAD

**Issue by brah-mcdude** [stryker-mutator/stryker-net#2366]
when i run stryker without a reporter, i get 2 timeouts. however, if i run stryker using the "cleartext" reporter, i get no timeouts in the report.

**Comment by rouke-broersma** [comment]
Could you give us examples of the reports? And is this consistent or could it perhaps be that if you run with the jtml report a couple times you get different results each time?

**Comment by brah-mcdude** [comment]
![image](https://user-images.githubusercontent.com/77924970/209578795-61e9cc39-6bc0-45de-acf4-33ee2a922e6c.png)

**Comment by brah-mcdude** [comment]
![image](https://user-images.githubusercontent.com/77924970/209579034-668df590-5fd3-46df-8fb6-933138619204.png)

**Comment by brah-mcdude** [comment]
as you can see, there are timeouts in the html reporter while there are none in the clear-text reporter.

**Comment by brah-mcdude** [comment]
![image](https://user-images.githubusercontent.com/77924970/209583777-c5e65182-d78f-4004-8144-5bae1008c028.png)

**Comment by brah-mcdude** [comment]
markdown reporter also has no timeouts.

**Comment by brah-mcdude** [comment]
![image](https://user-images.githubusercontent.com/77924970/209584633-8eb2fe8a-1809-4b6f-925a-42d2d2a36959.png)

**Comment by brah-mcdude** [comment]
latest run shows no timeouts in html reporter either. so i don't know what is going on. i don't think i changed the code in between these runs.

**Comment by brah-mcdude** [comment]
![image](https://user-images.githubusercontent.com/77924970/209584768-d5392397-0503-4106-8b30-cbdbcb04dbc6.png)

**Comment by brah-mcdude** [comment]
above is an example of a timeout. which makes no sense. the error calculation has no delays in it. it is just a summary of very few values (less than 10 values). is it possible to see the actual log file of the run? can i see the call stack of the timeout?

**Comment by brah-mcdude** [comment]
could it be that the timeout depends on my laptop cpu/memory being overloaded?

**Comment by brah-mcdude** [comment]
inoticed that the runs that produced the timeouts took 17 minutes. whereas the runs that did not produce timeouts took 7 minutes. i'm running a cpu stress app in the background. and re-running stryker. so we will soon see.

**Comment by dupdob** [comment]
hi. I think it may relates to your other issue (#2365).
Timeouts means the test run for that mutant took too long (typically more than twice the original run time + some buffer time, just in case). This usually means this mutation resulted in some infinite loop. Note that timeouts are considered as equivalent to kills.
The determination logic tries to differentiate between real timeouts and test sessions that took too much time because the computer entered sleep mode during the test run.
But alas, this detection is not 100% perfect, hence a sleep transition may result in timeout being reported instead of another results.

Do you see those timeouts subsequently to the computer entered sleep mode during the run?

**Comment by brah-mcdude** [comment]
![image](https://user-images.githubusercontent.com/77924970/209586132-fc814066-ef70-43c0-b7df-6238771842ff.png)

**Comment by brah-mcdude** [comment]
cpu stress app did a good job. the timeouts were very likely due to my laptop being overloaded.

**Comment by brah-mcdude** [comment]
i am closing this issue.
