### ISSUE TITLE
Multiple mutants might be active at the same time in solution runs

### ISSUE THREAD

**Issue by rouke-broersma** [stryker-mutator/stryker-net#2396]
Multiple mutants might be active at the same time when there is overlap between test projects and source projects. This is possible because an incremental mutant ID is used, but source projects are mutated individually. This means 2 source projects will have overlapping mutant IDs.

> But mutants used the same MutantControl.cs and when we choose ActiveMutant 1 then it going to apply two mutants in two 
projects. I tried to visualize it there 
<img width="561" alt="CleanShot 2023-01-29 at 11 52 11@2x" src="https://user-images.githubusercontent.com/10564511/215321270-8f7a5d55-2129-4e9c-a91e-e4b2b9ff8612.png">

_Originally posted by @codmw44 in https://github.com/stryker-mutator/stryker-net/issues/2381#issuecomment-1407629491_

**Comment by dupdob** [comment]
Working on an 'improve solution run PR'

**Comment by rouke-broersma** [comment]
@dupdob our quick-win solution was to simply use GUIDs instead of incremental IDs for the mutants. What was your thought?

**Comment by dupdob** [comment]
Wanted to discuss this. Not a big fan of GUIDs, as they would massively slowdown test phase, would be painful to search for in log files and would not look good in report.
I was thinking either using a global incremented identifier, i.e. as of today but making sure there are no conflicts across projects, or simply doing nothing.
Why doing nothing ? Because there is another issue: we inject mutation control once in each project, but with the same namespace. Not sure what happens exactly at run time, but my guess is that we end up having several instances of the class, and the datacollector identifies one at random (probably linked to load order).

This results in a lot of nasty side effects, such as failing to capture coverage, activating the wrong mutation and getting stupid result.

The fix for this is to ensure we have a unique namespace per project.
There are other issues with solution runs that I am reviewing, hence the idea to have a PR covering all identified issues at once.

That being said, how we identify mutations is still open for debate 😄
