### ISSUE TITLE
Stryker hangs for an empty code-test project pair

### ISSUE THREAD

**Issue by psfinaki** [stryker-mutator/stryker-net#2549]
**Describe the bug**
So yeah, it just hangs, after outputting this:

```
Version: 3.9.0

[16:57:49 INF] Analysis starting.
[16:57:59 INF] Found project C:\Users\xxx\Desktop\Repro\Code\Code.csproj to mutate.
[16:57:59 INF] Analysis complete.
[16:57:59 INF] Building test project C:\Users\xxx\Desktop\Repro\Tests\Tests.csproj (1/1)
[16:58:07 WRN] No test detected for project 'C:\Users\xxx\Desktop\Repro\Tests\Tests.csproj'. No cause identified.
[16:58:07 INF] Number of tests found: 0 for project C:\Users\xxx\Desktop\Repro\Code\Code.csproj. Initial test run started.
```

**Expected behavior**
Create an empty report or an error (not to crash the solution mode though).

**Additional context**
Note this is **a regression**, compared to at least 3.7.1, so we can't update. Prior to that, this was happening:
```
No test has been detected. Make sure your test project contains test and is 
compatible with VsTest.
```

Repro, for reference: [Repro.zip](https://github.com/stryker-mutator/stryker-net/files/11556157/Repro.zip)

**Comment by dupdob** [comment]
thanks
I had a quick look: I do reproduce the problems. So Stryker no longer stops when no tests are found (new behavior, quite deliberate), but fails to detect the end of (useless) initial test session.
Should be easy to fix 😄

**Comment by dupdob** [comment]
TIL that VsTest does not send any notifications if there is no test in the assembly, despite claiming otherwise in the log file.
And since it is the initial test session, there is no timeout set inside Stryker. As a reminder, Stryker adds an extra timeout logic on top of VsTest ones. This is due because: 
1. VsTest does not report time out situations, those look like normal runs, with some tests missing, or not (and they be missing for various reasons)
2. VsTest timeout logic may fail and the process may have to be killed.

That being said, I see two problems to fix here:
1. Stryker should not run test sessions when there is no test at all
2. Stryker should rely solely on VsTest when there is no timeout provided (as during initial tests)

**Comment by psfinaki** [comment]
Damn VsTest is really evil!
