### ISSUE TITLE
Microsoft.NET.Sdk.Razor.SourceGenerators.dll could not be loaded.

### ISSUE THREAD

**Issue by CzBuCHi** [stryker-mutator/stryker-net#2736]
**Describe the bug**
After **Initial test run started** message im getting this warning:
[17:34:51 WRN] Analyzer/Generator assembly C:\Program Files\dotnet\sdk\7.0.402\Sdks\Microsoft.NET.Sdk.Razor\targets\..\source-generators\Microsoft.NET.Sdk.Razor.SourceGenerators.dll could not be loaded.
Generated source code may be missing.

Warning has no effect on stryker behavior.

**Logs**
[logs.zip](https://github.com/stryker-mutator/stryker-net/files/13030619/logs.zip)

**Expected behavior**
No warning / link to page how to resolve.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Type of project: asp.net core
 - Framework Version 7.0
 - Stryker Version: 3.10.0

**Additional context**
Im not using any source generator in my code.

**Comment by rouke-broersma** [comment]
You're not using razor in your solution?

**Comment by CzBuCHi** [comment]
solution is aspnet core minimal api + ef core - no razor files

**Comment by ryanbell1997** [comment]
I had this issue with a completely different project, and all I needed to do to rectify was to update my IDE (VS2022) to the very latest version.

**Comment by dupdob** [comment]
Thanks for opening this issue, I share your desire for a clearer situation, but there are some caveats, alas:
1) As of today, there is now way for Stryker to identify an analyzer as (1) being (also?) a generator and (2) generating some code. So it is unlikely we can reach a point where this problem is silently ignored,
2) As of today, we have no clue on why an analyzer fails to load, so we are not able to provide useful direction.
3) Next release of Stryker will provide more information (everything Roslyn tells us) about why an analyzer fails to load. We hope this will help resolve individual cases as well as identify fixes and/or general guidance towards this problem
