### ISSUE TITLE
Safe mode causes 0 mutationscore when active

### ISSUE THREAD

**Issue by richardwerkman** [stryker-mutator/stryker-net#279]
When the new safe mode (#257) is activated it seems to cause a 0 mutationscore.

@dupdob Maybe you could take a look at this yourself?

**Comment by dupdob** [comment]
Of course

**Comment by dupdob** [comment]
I just realised that this is the expected behaviour! Without --dev-mode, Stryker will rollback all mutants in the failing method to allow for mutations to be tested.
With dev-mode, it fails directly, like previous versions.

What behaviour did you expect?

**Comment by richardwerkman** [comment]
Well it indeed rollbacks all mutants in the method. But all other mutants in the whole run are marked as survived in the end even though they should be killed. So it looks like the rollbacked method somehow causes that mutants can no longer be detected. This is not the expected behaviour! We would expect that all mutants in the rollbacked method get the status `builderror` and all others will be or `killed` or `survived` or `timeout`. So there is definitely a bug going on here.

**Comment by dupdob** [comment]
Here is what I have been able to reproduce using the integration test project, and injecting a construction that is bound to generate failure:
- the _safe mode_ is unable to restore the project to a compilable state
- the compilation error is not processed by Stryker's workflow logic
- all mutants are flagged as survivors since we are testing the original assembly

I will open an issue regarding the failure to handle the compilation error post rollback and improve/fix safe mode

**Comment by dupdob** [comment]
I just opened PR #285 that should fix your issue. Can you please test and confirm?
