### ISSUE TITLE
Support mutating default interface implementation

### ISSUE THREAD

**Issue by skarllot** [stryker-mutator/stryker-net#2809]
**Is your feature request related to a problem? Please describe.**
Since C# 8.0 default interface implementation is supported, then they should be mutated as well.

**Describe the solution you'd like**
The methods implemented on interfaces should be mutated as any other method.

**Describe alternatives you've considered**
Not applicable.

**Additional context**
```csharp
interface IA
{
    public void M() { Console.WriteLine("IA.M"); }
    public static void SM() { Console.WriteLine("IA.SM"); }
}
```

**Comment by dupdob** [comment]
Hi, thanks for reporting this.
I am afraid I do not have any issue with your sample. And while we do not have any test ensuring that default interface implementation works, there is no reason it should not work: Stryker does not skip interfaces.

I think the cause of your problem is different, in any case, we need more details to help you.

**Comment by dupdob** [comment]
Thanks.
There is no real problem here; Stryker simply does not have enough material for mutation: no expression, just method or constructor invocation as expression body.
There is a feature request about adding a mutator that would turn expression body into default expression: #2798 

I mark this issue as duplicate, feel free to comment previous issue if you have suggestion about this feature. 
You may also add a feature request for a new mutator if you have suggestions about what could be done for such construct.
