### ISSUE TITLE
No branch or tag or commit found with given target master

### ISSUE THREAD

**Issue by skarllot** [stryker-mutator/stryker-net#2823]
**Describe the bug**
Stryker is failing since 3.13.1 version.

**Logs**
```
[13:24:19 INF] Time Elapsed 00:04:53.5105569
Stryker.NET failed to mutate your project. For more information see the logs 
below:


No branch or tag or commit found with given target master. Please provide a 
different GitDiffTarget.
```

Full log: https://github.com/skarllot/Expressions/actions/runs/7438496458/job/20237310858#step:7:141

**Expected behavior**
Run without errors.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS
 - Type of project Library
 - Framework Version .NET 6.0
 - Stryker Version 3.13.1

**Additional context**
It runs without errors with the `since` configuration.

Ref: https://github.com/skarllot/Expressions/actions/runs/7438496458/job/20237310858#step:8:168

**Comment by rouke-broersma** [comment]
@skarllot ci tools usually perform a shallow fetch of only the **commit** that triggered the pipeline. This causes your branch refs to not be available, thus Stryker cannot find the master branch. Please make sure you have set your checkout steps to `fetch-depth: 0` or similar so the git history needed for since is available.

**Comment by rouke-broersma** [comment]
@skarllot 

The reason you didn't hit this issue before is because since was never actually enabled in your repo due to #2706. This was recently fixed which enabled since and caused your pipeline to stop working.

Please let me know if you have any other issues after adding the since compare target.

**Comment by rouke-broersma** [comment]
> Enabling since doesn't make it always run only for changed code?

It does, but there was a bug where `since` was not enabled implicitly by creating the object in the config file (instead you had to set since.enabled to true). That has now been fixed so now `since` is actually running on your project.

**Comment by dupdob** [comment]
I updated the issue tags to reflect this it is not an issue per se, but documentation/error messages could be made more helpful

**Comment by dupdob** [comment]
closing this issue
