### ISSUE TITLE
4.0.1 Errors with invalid RazorLangVersion '''

### ISSUE THREAD

**Issue by bonner-earle** [stryker-mutator/stryker-net#2881]
**Describe the bug**
Running a project that worked on 4.0.0, throws the error 

`Failed to generate source code for mutated assembly: error RZ3600: Invalid value ''' for RazorLangVersion. Valid values include 'Latest' or a valid version in range 1.0 to 8.0.
`
when run in 4.0.1 
The project doesn't contain any razor files
It is a .net 6 Azure app service  project
the build is running on Linux, running stryker 4.0.1 on my box (Windows 11) works 
We don't explicitly specify a razor lang version anywhere

**Logs**
Not got any as only occurs on our build server

**Expected behavior**
No error 

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu
 - Type of project Microsoft.NET.Sdk.Web
 - Framework Version .net 6
 - Stryker Version 4.0.1

**Additional context**
N/A

**Comment by rouke-broersma** [comment]
Can you provide us with a reproduction project?

**Comment by JackSteel97** [comment]
Just to note, we're experiencing this on 4.0.2 too for an ASP.NET 8 app that also doesn't use any Razor

**Comment by dupdob** [comment]
Thanks for providing a repro project. I do reproduce it, so I am able to analyze this issue. At this stage, I am unable to provide an ETA for a proper fix nor if there is a workaround.
Stryker only provide basic supports for code analyzers and generators, this mainly comes from the fact that there is little to no documentation on how to use these. Especially, we have yet to find a trustworthy source on how they are invoked during a normal build.

Some standard code generators and analyzers are invoked even when you do not explicitly reference them. The list depends on which SDK your project refers to. For Web, you have 3 default generators: JsonSourceGenerator, LoggerMessageGenerator and **RazorSourceGenerator**.

It turns out that the `RazorSourceGenerator` requires some setting to be set (see [code](https://github.com/dotnet/razor-compiler/blob/076fc261dcc1d51f5767e020114d713a65aa3788/src/Microsoft.NET.Sdk.Razor.SourceGenerators/RazorSourceGenerator.RazorProviders.cs#L45)). We have yet to understand how to pass this parameter properly.

Until we understand how to do it, the best we can do is continue even if there is an error at this stage. This will solve the problem for project not using Razor, but Razor project will keep failing (as of now, so this is not a regression)

**Comment by f-bourqui** [comment]
Same issue with 4.0.2.
4.0.0 works, but get 2 warnings :

_[11:37:46 WRN] Failed to load analyzer 'Microsoft.CodeAnalysis.Razor.Compiler.SourceGenerators':  (error : ReferencesNewerCompiler, analyzer: All).
[11:37:46 WRN] The analyzer 'Microsoft.CodeAnalysis.Razor.Compiler.SourceGenerators' references a newer version (4.9.0.0) of the compiler than the one used by Stryker.NET._
