### ISSUE TITLE
Stryker aborts when unsafe code blocks where used

### ISSUE THREAD

**Issue by fabianeichfeldt** [stryker-mutator/stryker-net#305]
My project includes a small part of unsafe code which results in a strange behaviour of stryker.
For testing purposes I've created a small project with an unsafe block.
[stryker-test.zip](https://github.com/stryker-mutator/stryker-net/files/2744169/stryker-test.zip)

**behaviour in V0.7.0**
 - in debugmode is an error printed 
  >  Compilation failed
  >    Unsafe code may only appear if compiling with /unsafe,

 - No mutant will be killed
 - no errormessages

**behaviour on master**
 - Abort with message:  
  >"Unsafe code may only appear if compiling with /unsafe"

So my easy and naive workaround and test was to enable the unsafe mode when the compiler is created.
(CompilingProgress.cs Line 52)
This works well for my test project and also for my real world project. But I've no idea which side effects are coming up with this. I think the best solution would be to activate this flag on demand. But I couldn't figure out a possibility to get the information if unsafe code blocks are used or if the system under test has enabled this flag.

**Comment by richardwerkman** [comment]
I don't think compiling with /unsafe has any side-effects on projects that contain no unsafe code. So enabling this by default could do no harm.

We should add this to both [CompilingProgress.cs](https://github.com/stryker-mutator/stryker-net/blob/master/src/Stryker.Core/Stryker.Core/Compiling/CompilingProcess.cs) and [InitialBuildProcess.cs](stryker-net/src/Stryker.Core/Stryker.Core/Initialisation/InitialBuildProcess.cs). Otherwise the initial build could still fail. I guess your initial build succeeds because of a setting in your .csproj file?

**Comment by fabianeichfeldt** [comment]
Thanks for your reply.

Yes, I have added this setting in my .csproj file. As far as I know is there no argument available for "dotnet build" to enable unsafe mode. 
So, I think we have to trust in the original settings of .csproj for the initial build.

I can commit my change(s) and create a pull request for this.

**Comment by richardwerkman** [comment]
Your PR would be very welcome. We could also read that setting from the users .csproj and enable unsafe mode if we find it. 

But since it's safe to enable this by default I wouldn't make this more complicated than needed.

**Comment by fabianeichfeldt** [comment]
I've created PR #306

**Comment by Mobrockers** [comment]
Closed by #306
