### ISSUE TITLE
Irelevant mutation

### ISSUE THREAD

**Issue by djkarlos** [stryker-mutator/stryker-net#3068]
**Describe the bug**
I am getting a mutation that can't be "killed" due to it incorrectly identifying a valid scenario.
The line of code is
`return decimal.Parse(amount) * (creditDebitIndicator == CreditDebitIndicatorEnum.DebitEnum ? -1 : 1);`
The mutation is claims has survived is
`return decimal.Parse(amount) \ (creditDebitIndicator == CreditDebitIndicatorEnum.DebitEnum ? -1 : 1);`
But mathematically they are identical and so there is nothing I can do to kill the mutant

**Logs**

**Expected behavior**
It should not attempt mutation on the line where mathematically there would be no difference

**Desktop (please complete the following information):**
 - OS: Windows
 - Type of project: core
 - Framework Version: .NET 8
 - Stryker Version: 4.3.0

**Additional context**

**Comment by dupdob** [comment]
### Short answer
I suggest you use [Stryker comments](https://stryker-mutator.io/docs/stryker-net/ignore-mutations/#stryker-comments) to disable the arithmetic operator for this line.
```csharp
// Stryker disable once arithmetic: result in equivalent code
return decimal.Parse(amount) * (creditDebitIndicator == CreditDebitIndicatorEnum.DebitEnum ? -1 : 1);
```
### Long answer
Stryker limits semantically equivalent mutations as much as possible, but we can only detect trivial situations. In your example, it is non trivial to detect that the second operand is always one (disregarding the sign) hence switching multiplier to divisor does not alter the result. There is no way Stryker can guarantee to eliminate all semantically, hence we only fix this type issue in narrow circumstances (trivial to detect and trivial to prevent). I am afraid we will not try and fix this one. 

### An alternative solution to Stryker comment
In practice, this kind of situation can often be addressed via a slight rewrite of the original code; semantic equivalence appears because there is some form of redundancy in the original code. Here there is no need for an actual multiplication.
It could be rewritten as is:
```csharp
return creditDebitIndicator == CreditDebitIndicatorEnum.DebitEnum ? -decimal.Parse(amount) : decimal.Parse(amount);
```
or introducing a local variable to avoid duplicating the call to parse
```csharp
var parsedAmount = decimal.Parse(amount);
return creditDebitIndicator == CreditDebitIndicatorEnum.DebitEnum ? -parsedAmount : parsedAmount;
```
Hope this helps.
