### ISSUE TITLE
Exclude files from mutating

### ISSUE THREAD

**Issue by richardwerkman** [stryker-mutator/stryker-net#34]
Right now, all `*.cs` files will be mutated by Stryker. Just like with code coverage, users would like to exclude some files.

I see two ways of excluding a file:

- Using an array of filenames as userinput
- By using Attributes inside the code

My preference goes to the attributes. Mainly because this option has more future posibilities like 

- excluding parts of files
- excluding only sertain mutators using different attributes.

This could look like:

``` csharp
namespace Stryker.Core.Testing
{
    [ExcludeFromStryker]
    public class ProcessExecutor : IProcessExecutor
    {
```

``` csharp
namespace Stryker.Core.Testing
{
    [ExcludeFromStryker("BinaryMutator")]
    public class ProcessExecutor : IProcessExecutor
    {
```

**Comment by michielpeeters** [comment]
I'll be happy to help with this issue. My suggestion would be to get rid of the magic strings and using enums for example. The only problem is when new mutators are introduced that the enum shoud be updated. Ow yeah, I fully agree that you should use attributes instead of using some sort of array. Or add some sort of configuration file where you can setup stryker (for example: nlog.config)?

**Comment by richardwerkman** [comment]
Nice to hear @michielpeeters! I think it would be best to start just with 
``` csharp
namespace Stryker.Core.Testing
{
    [ExcludeFromStryker]
    public class ProcessExecutor : IProcessExecutor
    {
```
The excluding of specific mutators could be another issue for later, if we want to.

This item could be a little hard since the attributes have to be looked for inside the AST's. If you need help please let us know!

**Comment by richardwerkman** [comment]
Hi @michielpeeters ,

After a quick search I've found the node type for attributes is `AttributeSyntax`. It has a name property.

A great start for this issue would be to ignore files completely if they contain a `[ExcludeFromStryker]` attribute. 

It would maybe look something like this:
``` csharp
syntaxTree.GetRoot().DecendentNodes().TypeOf<AttributeSyntax>().Any(node => node.Name == "ExcludeFromStryker")
```

If we want to exclude the whole file we could place it here:
https://github.com/stryker-mutator/stryker-net/blob/4650e0a71519c7f106e6d0ddc886ad3c183a28e8/src/Stryker.Core/Stryker.Core/MutationTest/MutationTestProcess.cs#L61

If we want to exclude only parts of files we would have to do this somewhere here:
https://github.com/stryker-mutator/stryker-net/blob/4650e0a71519c7f106e6d0ddc886ad3c183a28e8/src/Stryker.Core/Stryker.Core/Mutants/MutantOrchestrator.cs#L61

The second one is a bit more dificult is my guess. I hope this brings you up to speed with this item!

**Comment by michielpeeters** [comment]
Yeah I saw that already that the AttributeSyntax should be the way to go. This one contains a IdentifierSyntax which can resolve my string value to compare against "ExcludeFromStryker". I did already find out where the code should be located but thanks for pointing that out :-D!

My personal opinion and I'm not quite sure what it will do to speed, but I think if we can create a wrapper in the near future which analyzes the complete *.cs file and provides an object where we have for example: IsExcluded property (or something like that) with those kind of properties you will have more control in your code to enter the mutation process or not.

But first I'll try to find a nice and speedy way to exclude complete files :-).

**Comment by michielpeeters** [comment]
@richardwerkman if you have some spare time I've created a first implementation of the exclude attribute. You can find it here: https://github.com/michielpeeters/stryker-net when I have determined how to unit test the count of mutants I'll create a pull request. Maybe you have some better idea's about the unit test or the implementation :-).

**Comment by richardwerkman** [comment]
I'll take a look at this tomorrow! For now I've tried running your code and it crashes on:
https://github.com/michielpeeters/stryker-net/blob/72e6e3958ec962f7f7a5ebf280582426b0698f54/src/Stryker.Core/Stryker.Core/MutationTest/MutationTestProcess.cs#L83
Maybe you could already look at that.

**Comment by Mobrockers** [comment]
Imo it is bad practice to dirty your source files with attributes used only by an external testing tool. This way we force anyone that wants to use stryker exclusions to have a dependency on some stryker package in their source projects. I would prefer exclusions based on configuration using filepath patterns.

**Comment by kevinlyles** [comment]
If we want to eventually allow skipping only parts of a file (which I think would be useful), I think we have to do something at the source level.

**Comment by Mobrockers** [comment]
Can you give an example of a case in which you would want to exclude only parts of a file from mutation? The way I see it, the only reason to exclude parts of a file is because something is wrong with Stryker. In which case we have to fix the bug.

But besides that, if we do eventually need this, I would still want to have the option of file path based exclusion as well, in case I do not have any special cases where I want to exclude only a certain mutator from a certain file part.

I would suggest implementing file path pattern based configuration first. If we do actually need source level exclusion at some point (because someone brings forth a valid case for it) then we can decide at that point to implement it.

Right now I personally don't see any good reason to go this route. @richardwerkman @nicojs @simondel @yaelkeemink thoughts?

**Comment by michielpeeters** [comment]
Hi @Mobrockers, that's what I was thinking as well. Personally I don't have seen some sort of external runners using an attribute to control the flow of the runner. A configuration file, for example nlog.confg, is maybe better to control the flow (in the future) instead using attributes. I'm working on it now, sooo we can go every direction we want :-). What do you think @richardwerkman?

**Comment by richardwerkman** [comment]
I didn't think about the fact that the attributes should be placed inside the source project and not test project. It's not nice indeed that the source project should have a reference to some stryker package just for this attribute. So, if excluding part of a file is not a valid use case, my preference would go to reading an array from [the stryker config file](https://github.com/stryker-mutator/stryker-net/blob/master/src/Stryker.CLI/README.md#use-a-config-file). 

It could look like:
``` json
{
    "stryker-config":
    {
        "files-to-exclude": ["/startup.cs"],
    }
}
```

I think it's not needed to also exclude folders so it should only accept file names.

**Comment by kevinlyles** [comment]
I agree that having a full-file option that doesn't need changes to the source code under test is a good idea, and I think it probably makes sense to start with that.

However, I can definitely think of situations where I'd want to exclude some code in a file from needing mutation coverage, but still test the rest of the file.  Say you have a function to return the database id for some enum, or any other use case that gives you a simple switch with each branch just returning a constant.  Directly testing that is not very useful (the test would basically be the code again), and the indirect tests may live in other projects.  If there's also other code in that file, you'd want to exclude just that function.

Another case that would probably require an attribute would be disabling a particular mutation for a single file, or part of a file.

**Comment by michielpeeters** [comment]
Alright, sorry for the late reaction but I definitly prefer the file option. I'll start creating on the file option and that stryker will filter first on complete files. I'll create a PR from it and start with the implementation when inner or multiple classes are located. After that I'll filter on operation level which is now also easy to do because I can manipulate the syntaxTree with ease :-).

**Comment by hugo-vrijswijk** [comment]
Should be noted that both [Stryker4s](https://github.com/stryker-mutator/stryker4s/blob/master/docs/CONFIGURATION.md#files-to-mutate) and [Stryker](https://github.com/stryker-mutator/stryker/tree/master/packages/stryker#files-to-mutate) use the `mutate` option to specify which files should be mutated (or not mutated)

**Comment by michielpeeters** [comment]
Ok, I'm quite far with the implementation but having thoughts questions of how to handle it and how you guys like it.

1. Should it be case sensitive? For example: Recursive.cs and recursive.cs should both be accepted?
2. I find all the files by using '*.cs' as searchPattern. Within that method I'll verify if the file is included or excluded (based on the Stryker4s and Stryker mutate option). When you want to exclude you need to use the !. In the future we can extend it by filtering on folders etc. How you guys think about this approach?

**Comment by Mobrockers** [comment]
Exclusions should be unix glob filepath pattern based, see https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/file-matching-patterns?view=vsts and https://en.m.wikipedia.org/wiki/Glob_%28programming%29?wprov=sfla1, and should be case sensitive because the Linux file system is in most cases case sensitive. It has to be filepath based because there is no way to uniquely identify a file on filename only. Ideally there is a cross platform library that can handle this for us. 

I am not sure I agree with mutate ! Syntax because we already know by default what we should include (everything msbuild gives us). There should be almost no reason to need to include extra files and certainly should be no reason to have to configure anything for the default cases, almost all config should be excludes.

Also, we already mutate our source files now so we know which files we have and thus which are available for being pattern matched, why do we need to separately scan for *.cs files?

**Comment by jisperliu** [comment]
I would think there are use cases for excluding a/some functions. Some files have large amount of codes and some of them are not testable/no need to be tested. It would be great to see options that exclude specific function, and we can do that in the same fashion as the files.

**Comment by richardwerkman** [comment]
@jisperliu we are looking into ways of achieving that. We could indeed pass extra configuration to skip some methods. Another way would be to place attributes inside the code base. Any line/method/class decorated with the attribute would be skipped. What would you prefer?

**Comment by jisperliu** [comment]
@richardwerkman I feel decorators may be a better idea so that other teammates working on the project will have a straightforward image of what's being tested/excluded.

**Comment by kevinlyles** [comment]
I agree with decorators being the better approach.

**Comment by DougAtZonal** [comment]
I think both alternatives are needed. Decorators/attributes give a lot of flexibility but it's also useful to ignore generated code, identified by file name.

**Comment by Mobrockers** [comment]
I think all requested cases for excluding/including sources have been implemented now.
