### ISSUE TITLE
Should not be a mutant for ConfigureAwait(false)

### ISSUE THREAD

**Issue by kwlin** [stryker-mutator/stryker-net#421]
We have various async code in our libraries like:

```c#
await doSomething(context).ConfigureAwait(false);
```

Stryker-mutator change the false flag to true but most of the time it's for UnitTest purpose not interesting to change the flag to true.

**Comment by richardwerkman** [comment]
We could check the name of a method before mutating it's arguments. However we can't be sure that if the name is `ConfigureAwait` it is an async configuration. If we exclude this method (or maybe even more) we could also exclude methods that should be mutated. How do you think we should handle this?

**Comment by robertlyson** [comment]
Maybe we could implement one of following:
1. create a whitelist of public methods to be mutated based on the referenced projects(exclude nuget once).
2. create namespace exclude list which will remove methods from mutation process, in this case System.Threading.Tasks.*

**Comment by Mobrockers** [comment]
Number 2 won't work as we do not have that kind of information available at mutation time. I'm not sure what you have in mind with number 1.

**Comment by robertlyson** [comment]
Ad1. Ah, cool.
Ad2. 
For instance, if we are considering `ConfigureAwait(false)`, first we are checking from what type and then from what namespace it comes. Based on this information we can check if the namespace is being put on blacklist so we are excluding it from being mutated.

**Comment by Mobrockers** [comment]
Unfortunately it would be computationally expensive to determine type information for the syntax tree to mutate, so we will not be able to determine whether or not function is a member of a given namespace. We could have a guess based on found namespaces and known method names I suppose, but this would be a guess at best.

**Comment by kwlin** [comment]
I think for the first releases, it's oke to have a simple blacklist/exclude list based on then name of property/method.

But my prefer solution would be something like fully qualified name.

**Comment by anhaehne** [comment]
I've got a working prototype that allows to ignore by method name. I basically just return ´false´ in the `MutantOrchestrator.CanBeMutated` method, when the current `node` is a `InvocationExpression` and the method name is part of the ignored list. 

Would that be a suitable approach or is there a better way/place to implement the feature?

**Comment by Mobrockers** [comment]
I disagree with that solution because there is nothing inherently wrong
with the mutation. Imo the mutation should be placed but marked as
ignored/skipped immediately so that it's never executed. We could perhaps
add extra Metadata to indicate that it was skipped based on the ignore
list. This information imo must be present so that this detail is not lost
on the test result consumers.

**Comment by anhaehne** [comment]
Ok that is good to know.

I was thinking about introducing something like an `IMutationFilter` interface which is called in the `MutationTestProcess` after the mutants have been created. This would allow to implement different filters in the future. We could also move the `IgnoredFiles`-logic into a `MutationFilter`. [1]

These filter would mark mutants as ignore/skipped (or something similar) and we can ignore them later on and also display them in reporters as skipped.

Should they be displayed in the HTML-reporter?

[1] That would of cause mean we would create mutations for ignored files. Since mutant creation is the smallest part of the actual execution i think this would still be worth the overhead.

**Comment by anhaehne** [comment]
I have a working version under:
https://github.com/anhaehne/stryker-net/commit/d73425afae78d21fa30cfeab640b7defbbc3ea78

Console output could look something like this:
![image](https://user-images.githubusercontent.com/5433898/62202680-027b3b00-b38a-11e9-9d53-6fca641abc7d.png)
