### ISSUE TITLE
Multi project runs: Mutate more projects at once

### ISSUE THREAD

**Issue by SierraNL** [stryker-mutator/stryker-net#459]
In a situation where you use both normal unittests and SpecFlow tests, you can end up with two test projects, testing the same implementation project.

Now you have to run stryker twice and you end up with two results. Which probably have a certain amount of overlap.

It would be helpful if you can merge the results, or even better, run both projects at once, so you have only one result.

**Comment by richardwerkman** [comment]
This would indeed be a cool feature! I'd like to see a way to tell stryker what projects to mutate and what test projects to run. Performance wise this would be a killing feature. We may need to think about ways to minimize the number of testruns.

For example: `project.x` has two test projects: `testproject.x` and `testproject.y`. And `project.z` has one test project: `testproject.z`.

That way we know we won't have to run `testproject.z` for mutations made in `project.x`. 

With this feature we should immediately build the merging of the html reports.

**Comment by richardwerkman** [comment]
I discussed this with @Mobrockers today and we see two aproaches for this. 

* Always run from the solution file and run all unit tests and mutate all logic
    * On no configuration, all logic will be mutated
* Always run from a test project and include more unit test projects or more logic projects
    * On no configuration, only 1 logic project will be mutated

The first option seems to have some advantages over the second one:
* Buildalyzer is more precise when the solution path is always given
* With no configuration, a full report will be generated

The second option also has an advantage:
* Running from the solution file can be hard to configure on large projects (10+ csproj files) and be very slow

**Comment by richardwerkman** [comment]
Today I've created a design for the multi project run feature.

It looks like this:

![image](https://user-images.githubusercontent.com/14224500/58338393-11a0b280-7e48-11e9-8031-06a8babded85.png)

The idea is that we'll place a config file in each project. This makes excluding files possible in each project that should be mutated. This also keeps the current way of running stryker possible. That way we stay backwards compatible.

I'll create smaller issues to get to the final design in smaller steps.

**Comment by OskarKlintrot** [comment]
Is there any documentation on how to make this work? I added a `stryker-config.json` to my root (where my .sln-file is) and one to each project that contains which test projects to run. When I then run `dotnet stryker` or `dotnet stryker --solution MySolution.sln` in the root it says:
```
No .csproj file found, please check your project directory at C:\...
```

**Comment by rouke-broersma** [comment]
Hi @OskarKlintrot 

Unfortunately we cannot recommend using solution runs at this time, because you will almost guaranteed hit #1665 if you do.

Because of this we have never 'officially' released this feature and don't point it out in documentation. 

Adding a stryker-config to each of your projects is not supported, only the stryker-config in the root is used. Stryker then calculates based on project references which test projects relate to which sut projects.

Could you share what your stryker-config looks like and create a new bug with this information? Confidential information can be removed. Your description of the process sounds like the correct way to use solution runs.

**Comment by OskarKlintrot** [comment]
@rouke-broersma I see, thanks for your reply!

I was playing around in a side project of mine that's OSS so I can share everything you want :) This is how I assumed it should be set up based on [the picture above](https://github.com/stryker-mutator/stryker-net/issues/459#issuecomment-495675297): https://github.com/OskarKlintrot/UpdatR/commit/a51b041960f72d82ba6bf09e990df331f28f6084. Since I didn't set it up correctly, I assume I didn't hit a bug :) Or should something happen, just that the nested stryker-config.json-files gets ignored?

At work (where I actually wants to run Stryker, in my side-project only one project is worth running stryker against) our solutions look very similar to [this](https://github.com/OskarKlintrot/UpdatR/commit/a51b041960f72d82ba6bf09e990df331f28f6084).

**Comment by rouke-broersma** [comment]
The feature should ~work~ _start_, I just expect that the nested stryker-config files are ignored and that you will eventually hit the bug I linked.

**Comment by OskarKlintrot** [comment]
Interesting, all I get is this:
```
No .csproj file found, please check your project directory at C:\repos\UpdatR
```
I have hit the bug twice when running against a single project though.

**Comment by rouke-broersma** [comment]
I can reproduce this on my machine, this is a regression of some sorts.
