### ISSUE TITLE
TotalNumberOfTestsParser.ParseTotalNumberOfTests fail under certain language settings

### ISSUE THREAD

**Issue by PovlPE** [stryker-mutator/stryker-net#561]
The ParseTotalNumberOfTests method takes the testrunner result as an inpuit, e.g.:
Test Run Successful.
Total tests: 2
     Passed: 2
 Total time: 1.4325 Seconds

Here the look for the end of the line with a "." token. However in certain languages, among here danish, we use a "," to separate full seconds from the decimals. This causes the method to fail.

**Comment by Mobrockers** [comment]
I believe your issue should be fixed with the recently merged pr #556 

We will probably release a new stryker version including this fix this friday.

**Comment by PovlPE** [comment]
I believe you are right. The errors seems to be the exact same.
I will verify Monday and close this if it is fixed.

**Comment by Mobrockers** [comment]
@PovlPE We have merged this to master but were unable to release a new version last week. We have also decided to remove the TotalNumberOfTestsParser completely and replace it with testrunner integrateion to discover the total number of tests, due to the amount of bugs that keep propping up with TotalNumberOfTestsParser.

**Comment by PovlPE** [comment]
I looked at the master for the TotalNumberOfTetsParser, and the dependency of the "." was removed and assumed it was working =)
Any idea of when the new integration will be completed?

**Comment by Mobrockers** [comment]
The PR is open: #566 

It just needs reviewing and approval
