### ISSUE TITLE
Feature request: support source file identification with buildalizer

### ISSUE THREAD

**Issue by dupdob** [stryker-mutator/stryker-net#897]
Stryker should support alternate ways to identify the source files of the mutated project, instead of scanning the project folder(s) for .cs files. 

For example, it could use BuildAlyzer results as a reliable source.

**Comment by Mobrockers** [comment]
We have time on Friday to take a good look at this if you can provide us with the working PoC.

**Comment by dupdob** [comment]
I can open à PROPOS. But it turned out quite easy. I could open à PR after a bit of refactoring effort.
The other open point is how to name the related option, but I can left it as is (hard coded if) so you can add the control logic that makes sense for the product

**Comment by Mobrockers** [comment]
If it works I don't see any reason to keep the old way. If it does turn out to not work in all cases we'll think about what to do with the option in that case. Perhaps we'll just make it so it tries compiling with the buildalyzer sources and if it fails to try manual finding the files for example.

I am surprised it was so easy because as far as I can remember buildalyzer does not handle shared projects: https://github.com/daveaglick/Buildalyzer/issues/85 🤷‍♀

**Comment by dupdob** [comment]
I think ‘it just works’. I haven’t read much on Buildalizer, but it looks like it spies on MsBuild while building the project.
I has to exclude the assemblyinfo.cs file generated on the fly to inject version information..
