### ISSUE TITLE
Restrict ignore methods to only method invocations

### ISSUE THREAD

**Issue by rouke-broersma** [stryker-mutator/stryker-net#973]
>> This will cause the `--ignore-methods` option to be quite expanded. Could you please update the documentation?

> I'm not sure if I still want this myself since I already dislike the ambiguity of given filter. The use of excluding method-calls seems appropriate since one can't really test the mutations on `ConfigureAwait` for example but excluding method-bodies (like it already does) is a whole different beast.

> Since you already accepted my other PR where I can opt-out of testing with the `ExcludeCoverage` attribute you maybe want to restrict this feature even more.

_Originally posted by @riezebosch in https://github.com/stryker-mutator/stryker-net/pull/961#issuecomment-597046635_

**Comment by Mobrockers** [comment]
As per the suggestion by @riezebosch we are considering restricting the ignore-methods feature to only consider methods invocations. This feature is useful because ConfigureAwait etc cannot easily be excluded by ExcludeCoverage attribute. All other exclusion cases can more easily be ignored by ExcludeCoverage attributes.

If anyone disagrees with this change, please let us know.

**Comment by richardwerkman** [comment]
I agree with this. It no longer makes sense to also ignore the whole method as we have the attribute for that now. However if we go through with this the name of the options becomes a bit unclear. We might have to rename it. I suggest: `--ignore-method-invocations`

**Comment by richardwerkman** [comment]
I think this is already done. I added a test and it succeeded without a code change. I'll create a PR
